"""文本结构重建：把「版面行流」还原为「段落流」（纯函数，无 IO、无第三方依赖）

问题
----
``pypdf.PdfReader.pages[i].extract_text()`` 默认产出的是**版面行**：同一段落在页面上
被折成多行，而「段内折行」与「段落边界」**都表现为单个 ``\\n``**。实测 310 页中文
PDF 中 ``\\n\\n`` 出现 **0 次**，于是分块器分隔符链的第一级 ``"\\n\\n"`` 永远不可达，
实际只能命中第二级 ``"\\n"``；又因版面行均长仅 37.5 字符、永不触及 ``chunk_size``，
第三级 ``"。"`` 同样不会被触发。分块因此退化为「按版面行装箱到 chunk_size」——
块边界与语义边界无关，实测 **82.5% / 87.2% 的块在句子中间被切断**。

解决办法
--------
在**解析层**把版面行流还原为段落流：段内折行合并为一行，段落之间用 ``\\n\\n`` 连接。
这样 ``\\n\\n`` 成为真实可达的结构边界，分块器**无需改动**即可按结构落刀。

三条处理规则
------------
1. **噪声行剔除**——页码行、目录点线行、纯符号行、跨页高频重复的页眉/页脚行。
   这类内容会污染稠密向量与 BM25 词频（实测目录点线 ``. . . . . 5`` 曾被当作正文入库）。
2. **硬折行合并**——上一行不以句末标点结尾，且下一行不是新的结构单元（列表项 / 章节
   标题）⇒ 二者属同一段，直接拼接（中文直连；两侧均为 ASCII 字母数字时补一个空格，
   避免 ``tokenA`` 与 ``tokenB`` 粘连成 ``tokenAtokenB``）。
3. **段落连接**——段落之间以 ``\\n\\n`` 连接。

为什么**不**按「行长是否顶到右边距」推断段落结束
-----------------------------------------------
直觉做法是估算版面的折行宽度，把「明显短于折行宽度的行」当作段落末行。实测**否决**：
该启发式会产生大量**版面驱动**的伪段落断点。以本项目两份真实 PDF 为例，把该阈值从
「关闭」逐步放宽后，块边界的对齐率确实上升（段界率 94% → 99%，切断率 5.8% → 1.0%），
但代价是段落断点里「由句末标点或结构标记驱动」的比例从 **97%/90% 崩到 24%/27%**——
即四分之三的 ``\\n\\n`` 都插在了句子中间，问题只是从「块边界任意」变成「段落边界任意」。
故本模块只依赖**确定性信号**（句末标点 + 列表项/章节标题标记），不做版式推断。
标定数据见 ``docs/chunking-quality-baseline.md``。

本模块只剔除**可判定为非正文**的噪声行，不承担内容清洗职责——任何存疑的行一律保留。
误删正文的代价远高于留下一行噪声。

另一条已被实测否决的路径
------------------------
``pypdf`` 的 ``extraction_mode="layout"`` 确实能恢复段落结构（实测 ``\\n\\n`` 从 0 →
146），但会**吞掉英文词间空格**（``Generated by Agent framework`` →
``GeneratedbyAgentframework``），并注入大量版面对齐留白（字符总量膨胀 +25%）。前者
直接破坏 BM25 对英文标识符的分词，后者浪费本就紧张的 448 字符预算。故不采用；
此结论在此记录，以免后续重复评估。

确定性
------
本模块全部为纯函数：同一输入恒得同一输出，不含随机、时间、IO、环境依赖。
分块结果参与 ``vector_id`` 推导，故确定性是可复现性的前提。
"""
from __future__ import annotations

import re
from collections import Counter
from typing import Dict, List, Optional, Sequence, Set

#: 中文/通用句末标点。ASCII 句号另有单独判据（见 :func:`ends_sentence`）。
SENTENCE_END = "。！？；…!?"

#: 句末标点后可能紧跟的收尾符号，判定时需先剥掉（``。”`` ``。）`` 等）。
TRAILING_CLOSERS = "”’」』》〉）)】]\"'"

#: 英文句末标点：句号/问号/感叹号结尾，且**前一字符不是数字**。
#: 排除数字是为了不把 ``v2.0`` ``2026.`` 这类版本号、序号误判为句子结束。
_ASCII_SENTENCE_RE = re.compile(r"(?<![0-9])[.?!]$")

#: 纯页码行：``12`` ``- 12 -`` ``第 12 页`` ``· 12 ·``
_PAGE_NUMBER_RE = re.compile(r"^[-—–·•\s]*(?:第\s*)?\d{1,4}(?:\s*页)?[-—–·•\s]*$")

#: 目录点线：``....`` ``. . . . .`` ``……``（允许点之间夹杂空格）
_DOT_LEADER_RE = re.compile(r"(?:[.·…⋯]\s*){4,}")

#: 列表项起点：``- x`` ``* x`` ``• x`` ``1. x`` ``(1) x`` ``一、x``
_BULLET_RE = re.compile(
    r"^\s*(?:[-*+•·▪◦]|\(?\d{1,3}[.)、）]|[（(]?[一二三四五六七八九十百]+[、.)）])\s*"
)

#: 章节标题起点：``第 3 章`` ``3.2 标题`` ``# 标题`` ``附录 A`` ``图 3-1``
_SECTION_RE = re.compile(
    r"^\s*(?:第\s*[一二三四五六七八九十百零\d]+\s*[章节篇部讲]"
    r"|#{1,6}\s"
    r"|\d{1,2}(?:\.\d{1,2}){1,3}\s*[、.]?\s*\S"
    r"|附录\s*[A-Z0-9一二三四五六七八九十]"
    r"|[图表格]\s*\d+[-–—.]\d+)"
)

#: 判定「一行是否有实际内容」：至少含一个字母/数字/汉字。
#: 用于识别分隔线（``-----``）、装饰行等纯符号行。
_HAS_CONTENT_RE = re.compile(r"[\w\u4e00-\u9fff]")


# ────────────────────────────── 行级判据 ──────────────────────────────


def ends_sentence(text: str) -> bool:
    """判断一行文本是否以句末标点结束（先剥掉 ``”）`` 这类收尾符号）

    这是「该行是段落的最后一行」的主判据，因而直接决定段落切在哪里。
    """
    stripped = text.rstrip().rstrip(TRAILING_CLOSERS)
    if not stripped:
        return False
    if stripped[-1] in SENTENCE_END:
        return True
    return bool(_ASCII_SENTENCE_RE.search(stripped))


def normalize_for_dedup(line: str) -> str:
    """把一行归一到「只保留内容字符」的形式，用于跨页重复行检测

    去掉全部空白是刻意的：页眉常带页码（``第 3 章 概述    12``），逐页不同，
    不归一就无法识别为同一行。
    """
    return re.sub(r"\s+", "", line)


def is_noise_line(
    line: str,
    running_lines: Optional[Set[str]] = None,
    *,
    keep_dot_leaders: bool = False,
) -> bool:
    """判断一行是否为应剔除的噪声（页码、目录点线、纯符号行、页眉页脚）

    仅删除**可判定为非正文**的行；任何存疑的行一律保留——本模块的目标是还原结构，
    不是做内容清洗，误删正文的代价远高于留下一行噪声。

    Args:
        keep_dot_leaders: 保留带引导点线的目录条目。目录页上点线**正是判据本身**：
        先剔噪声会把「这页是目录」的证据一起删掉，导致既识别不出目录、又把目录条目
        当成正文入库。故结构解析在目录页上须置 ``True``（见
        :func:`app.utils.structure_blocks.build_blocks`）。
    """
    stripped = line.strip()
    if not stripped:
        return True
    if not _HAS_CONTENT_RE.search(stripped):
        return True
    if _PAGE_NUMBER_RE.match(stripped):
        return True
    if not keep_dot_leaders and _DOT_LEADER_RE.search(stripped):
        return True
    if running_lines and normalize_for_dedup(stripped) in running_lines:
        return True
    return False


def detect_running_lines(
    pages: Sequence[str],
    min_pages: int = 5,
    min_ratio: float = 0.5,
    max_chars: int = 100,
) -> Set[str]:
    """识别跨页高频重复的行（页眉 / 页脚 / 水印），返回其归一化形式集合

    Args:
        pages: 各页的原始提取文本
        min_pages: 少于该页数不做检测——样本太小时「重复」可能只是正常行文
        min_ratio: 出现在该比例的页面上才算重复
        max_chars: 长度上限。页眉/页脚都短；限制长度可避免误删反复出现的长正文段落

    只统计**每页去重后**的存在性：同一行在一页里出现多次只计一次，
    否则一页内部的重复会把无关行推过阈值。
    """
    nonempty = [p for p in pages if p and p.strip()]
    if len(nonempty) < min_pages:
        return set()

    counter: Counter = Counter()
    for page in nonempty:
        seen = {
            normalize_for_dedup(line)
            for line in page.split("\n")
            if line.strip() and len(normalize_for_dedup(line)) <= max_chars
        }
        for norm in seen:
            if norm:
                counter[norm] += 1

    threshold = max(2, int(len(nonempty) * min_ratio))
    return {norm for norm, count in counter.items() if count >= threshold}


def starts_structural_block(line: str) -> bool:
    """该行是否是一个**新结构单元**的起点（列表项 / 章节标题）

    公开导出：诊断脚本需要用与重建器**完全相同**的判据来评估「段落断点是否落在
    语义边界上」，否则护栏指标与算法行为会对不上。
    """
    stripped = line.lstrip()
    return bool(_BULLET_RE.match(stripped) or _SECTION_RE.match(stripped))


# ────────────────────────────── 段落重建 ──────────────────────────────


def join_wrapped(previous: str, current: str) -> str:
    """合并「本应在同一行/同一段」的两段文本

    中文（及中英混排的中文侧）直接拼接——加空格会引入原文没有的切分点，反而伤害
    BM25；仅当**两侧都是 ASCII 字母数字**时补一个空格，避免英文单词粘连。

    公开导出：结构解析模块用它拼接**同一行内的多个版式片段**（PDF 的一行常被拆成
    数个 ``Tj``/``TJ`` 片段）。两处必须用同一套粘连判据，否则同一份文档经不同路径
    会产出不同文本。
    """
    if not previous:
        return current
    left, right = previous[-1], current[0]
    if left.isascii() and left.isalnum() and right.isascii() and right.isalnum():
        return f"{previous} {current}"
    return previous + current


def _starts_new_paragraph(previous: str, current: str) -> bool:
    """判断 ``current`` 是否应另起一段（而非上一行的折行续写）

    两条判据，都是**确定性信号**，任一成立即断开：

    1. 上一行以句末标点结尾 —— 句子已结束，硬证据；
    2. 本行是新结构单元的起点（列表项 ``- x`` / ``1. x``，或章节标题 ``第 3 章``
       ``3.2`` ``附录 A``）—— 结构单元天然独立成段。

    刻意**不使用**「行长是否顶到右边距」这类版式推断：实测它会把四分之三的段落断点
    变成版面驱动（即插在句子中间），详见模块文档的同名小节。
    """
    if ends_sentence(previous):
        return True
    return starts_structural_block(current)


def rebuild_paragraphs(
    text: str,
    running_lines: Optional[Set[str]] = None,
) -> str:
    """把一页（或一份文本）的版面行流还原为段落流

    Returns:
        段落之间以 ``\\n\\n`` 连接、段内折行已合并的文本。噪声行被剔除；
        其余字符按原顺序保留。
    """
    lines = text.split("\n")

    paragraphs: List[str] = []
    buffer: Optional[str] = None

    for raw in lines:
        if is_noise_line(raw, running_lines):
            # 噪声行同时也是天然的结构断点：页眉/页码之后必然是新的段落
            if buffer is not None:
                paragraphs.append(buffer)
                buffer = None
            continue

        stripped = raw.strip()
        if buffer is None:
            buffer = stripped
        elif _starts_new_paragraph(buffer, stripped):
            paragraphs.append(buffer)
            buffer = stripped
        else:
            buffer = join_wrapped(buffer, stripped)

    if buffer is not None:
        paragraphs.append(buffer)

    return "\n\n".join(p for p in paragraphs if p)


def rebuild_pdf_pages(pages: Sequence[str]) -> List[str]:
    """对 PDF 各页批量做段落重建

    **输出与输入等长同序**：每页一个元素，页号由调用方按下标推导。这一契约不能破，
    否则块的 ``source_page`` 会整体错位（比元数据缺失更糟）。

    Args:
        pages: 各页 ``extract_text()`` 的原始输出（空白页的 ``None`` 须先由调用方归一为 ``""``）

    Returns:
        与 ``pages`` 等长的段落化文本列表
    """
    running_lines = detect_running_lines(pages)
    return [rebuild_paragraphs(page, running_lines) for page in pages]


def noise_statistics(pages: Sequence[str]) -> Dict[str, int]:
    """统计噪声剔除情况，供日志与诊断脚本观测

    Returns:
        ``{"lines": 总行数, "noise": 噪声行数, "running": 页眉页脚行数, "pages": 页数}``
    """
    running_lines = detect_running_lines(pages)
    lines = 0
    noise = 0
    from_running = 0
    for page in pages:
        for line in (page or "").split("\n"):
            lines += 1
            if is_noise_line(line):
                noise += 1
            elif running_lines and normalize_for_dedup(line) in running_lines:
                from_running += 1
    return {
        "pages": len(pages),
        "lines": lines,
        "noise": noise,
        "running": from_running,
    }
