"""refactor users table

Revision ID: 6134fce0bd30
Revises: 0c40119b0854
Create Date: 2026-05-29 21:11:05.486389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6134fce0bd30'
down_revision: Union[str, Sequence[str], None] = '0c40119b0854'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('roles', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('tenants', sa.Column('plan', sa.String(length=50), nullable=False))
    op.add_column('tenants', sa.Column('max_users', sa.Integer(), nullable=False))
    op.add_column('tenants', sa.Column('max_models', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login_at')
    op.drop_column('tenants', 'max_models')
    op.drop_column('tenants', 'max_users')
    op.drop_column('tenants', 'plan')
    op.drop_column('tenants', 'description')
    op.drop_column('roles', 'description')
    op.drop_column('permissions', 'description')
    # ### end Alembic commands ###
