"""add deleted_at to ai_providers

Revision ID: 7510768bb805
Revises: f5f8de306747
Create Date: 2026-06-30 13:59:32.545231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7510768bb805'
down_revision: Union[str, Sequence[str], None] = 'f5f8de306747'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_providers', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_providers', 'deleted_at')
    # ### end Alembic commands ###
